name: Docker Image - Frontend

on:
  push:
    paths:
      - 'frontend/pages/**'
      - 'frontend/components/**'
      - 'frontend/styles/**'
      - 'frontend/public/**'
      - 'frontend/Dockerfile'
    branches:
      - master


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file ./frontend/Dockerfile --tag tolfixorg/tlx-frontend:latest
      - name: Docker push
        run: docker push tolfixorg/tlx-frontend:latest